Add logging ability.
fynelabs/selfupdate pull request #18
Opened 2022-06-08 21:09 UTC by Bluebugs

2022-06-08 21:09 UTC, Bluebugs commented
This should help address #17 in a generic way.

2022-06-08 21:15 UTC, Bluebugs commented
I did spend a little bit of time looking at a few log module for golang and there is no interface except at the function level which is why I settle for just going with a Printf style prototype that is supported by all the module I checked.

2022-06-09 20:50 UTC, andydotxyz requested changes
Great addition - but some typos and unneeded variable initialisation

2022-06-09 20:50 UTC, andydotxyz commented on README.md
> +## Loggin
Maybe Logging?

2022-06-09 20:50 UTC, andydotxyz commented on README.md
> +We provide three package wide variable: `LogError`, `LogInfo` and `LogDebug` that follow `log.Printf` API to provide an easy way to hook any logger in. To use it with go logger, you can just do
"variables"

2022-06-09 20:50 UTC, andydotxyz commented on log.go
> +var LogError func(string, ...interface{}) = nil
These ` = nil` should not be needeed, all variables default to the zero value, for a `func` that is `nil`

2022-06-09 21:22 UTC, andydotxyz approved these changes
Great thanks

2022-06-10 15:00 UTC, merged