Add ScheduleAt ability.
fynelabs/selfupdate pull request #20
Opened 2022-06-10 17:38 UTC by Bluebugs

This should address #19

2022-06-10 17:43 UTC, Bluebugs commented
This should addres #19.

2022-06-10 17:45 UTC, Bluebugs commented
I think this PR should help @jtdaad schedule update during office off hours.

2022-06-13 09:54 UTC, andydotxyz requested changes
Complexity is drastically increased here - see comments inline for how it could be improved.
If we think test first it will be clear that this code needs to be tidied.

2022-06-13 09:54 UTC, andydotxyz commented on updater.go
> +	Minutly           // Will schedule in the next minute and repeat it every minute after
Can we remove this? No application should try and update every minute!

2022-06-13 09:54 UTC, andydotxyz commented on cmd/example/main.go
> +			Interval:     time.Minute * time.Duration(60),
I don't know if this is a good example - as the "ScheduleAt" will happen in addition to every hour after start...

2022-06-13 09:54 UTC, andydotxyz commented on updater.go
> +					case Minutly:
This really should be factored out into another method that determines what the "next time" for a schedule.
That can also then be tested - this is some pretty clever date manipulation that has no tests.

2022-06-13 09:54 UTC, andydotxyz commented on updater.go
> +					updater.CheckNow()
Ignored error

2022-06-13 09:54 UTC, andydotxyz commented on updater.go
> +			go func() {
This is not too cool, we now have 2 goroutines spawning from within a goroutine none of which has date tests.
This would be so much cleaner if this single goroutine was able to get the next time to trigger from a helper (tested) function, then we don't need 3 goroutines and 2 separate inner for loops.

2022-06-14 08:28 UTC, andydotxyz requested changes
Much cleaner thanks, just a little misleading naming to resolve.

2022-06-14 08:28 UTC, andydotxyz commented on cmd/example/main.go
> +			// If you want to check update on a regular interval uncomment the follwoing
"following"

2022-06-14 08:28 UTC, andydotxyz commented on updater.go
> +		var next time.Duration
Sorry to be picky, but `next` is a time not a duration, perhaps "offset" or "delta" or "delay" etc might work better?

2022-06-14 08:28 UTC, andydotxyz commented on updater.go
> +func nextScheduleAt(repeating Repeating, offset time.Time) time.Duration {
Much like the comment above this name implies returning a time but it returns a duration.
Perhaps "delayUntilNextTrigger" or "offsetToSchedule" etc?

2022-06-15 18:10 UTC, andydotxyz reviewed
Looking good, but some missing docs.

2022-06-15 18:32 UTC, andydotxyz approved these changes
Cedric promised the docs in next PR :)

2022-06-15 18:33 UTC, merged